FROM osrf/ros:noetic-desktop-full

LABEL maintainer="Haoyu Wang (qrpucp@qq.com)"

ENV DEBIAN_FRONTEND noninteractive

# use bash instead of sh to use source
SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get upgrade -y && \
    apt-get install git apt-utils python3-pip -y && \
    apt-get install git python3-catkin-tools -y && \
    rosdep update

# install vim and htop
RUN apt-get install vim htop -y

# install tmux and oh-my-tmux
WORKDIR /root
RUN apt-get install tmux -y && \
    git clone https://github.com/gpakosz/.tmux.git && \
    ln -s -f .tmux/.tmux.conf && \
    cp .tmux/.tmux.conf.local .

# install zsh, oh-my-zsh and zsh extensions
WORKDIR /root
RUN apt-get install zsh curl -y && \
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

WORKDIR /root/.oh-my-zsh/custom/plugins
RUN git clone https://github.com/zsh-users/zsh-autosuggestions.git && \
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git && \
    sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/' /root/.zshrc

# install vscode (code-server)
RUN curl -fsSL https://code-server.dev/install.sh | sh

# install Node.js 20.x
RUN apt-get update && apt-get install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get update && apt-get install nodejs -y

# install dependencies in config.json
WORKDIR /root/scripts
COPY build.py /root/scripts/build.py
COPY config.json /root/scripts/config.json
RUN python3 /root/scripts/build.py

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

WORKDIR /
CMD [ "zsh" ]
